"use client";

import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { Activity, Flame, Loader2, MapPin, MousePointer2, Video } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

type Overview = {
  since: string;
  sessions7d: number;
  events7d: number;
  replaySegments7d: number;
  heatmapPoints7d: number;
  surveysTotal: number;
  latestFriction: Array<{
    id: number;
    page: string;
    summary: string | null;
    rageClicks: number | null;
    deadClicks: number | null;
    createdAt: string;
  }>;
  note?: string;
};

export default function BehaviorIntelligenceOverviewPage() {
  const { data, isLoading, isError } = useQuery({
    queryKey: ["/api/admin/behavior-intelligence/overview"],
    queryFn: async () => {
      const res = await apiRequest("GET", "/api/admin/behavior-intelligence/overview");
      return res.json() as Promise<Overview>;
    },
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[40vh]">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (isError || !data) {
    return <p className="text-destructive text-sm">Could not load Behavior Intelligence overview.</p>;
  }

  const links = [
    { href: "/admin/behavior-intelligence/replays", label: "Session replays", icon: Video },
    { href: "/admin/behavior-intelligence/heatmaps", label: "Heatmaps", icon: MousePointer2 },
    { href: "/admin/behavior-intelligence/surveys", label: "Surveys", icon: MapPin },
    { href: "/admin/behavior-intelligence/user-tests", label: "User tests", icon: Activity },
    { href: "/admin/behavior-intelligence/friction-reports", label: "Friction reports", icon: Flame },
  ];

  return (
    <div className="max-w-6xl mx-auto px-4 py-8 space-y-8">
      <div className="flex flex-col gap-2">
        <h1 className="text-2xl font-bold tracking-tight">Behavior Intelligence</h1>
        <p className="text-muted-foreground text-sm max-w-3xl">
          Session replay, heatmaps, surveys, and friction signals. Extends <code className="text-xs bg-muted px-1 rounded">visitor_activity</code>{" "}
          without replacing it. Ingest: <code className="text-xs bg-muted px-1 rounded">POST /api/behavior/ingest</code>.
        </p>
        {data.note ? <p className="text-xs text-muted-foreground">{data.note}</p> : null}
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Sessions (7d)</CardTitle>
          </CardHeader>
          <CardContent className="text-2xl font-semibold">{data.sessions7d}</CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Behavior events (7d)</CardTitle>
          </CardHeader>
          <CardContent className="text-2xl font-semibold">{data.events7d}</CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Replay chunks (7d)</CardTitle>
          </CardHeader>
          <CardContent className="text-2xl font-semibold">{data.replaySegments7d}</CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Heatmap points (7d)</CardTitle>
          </CardHeader>
          <CardContent className="text-2xl font-semibold">{data.heatmapPoints7d}</CardContent>
        </Card>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {links.map(({ href, label, icon: Icon }) => (
          <Button key={href} variant="outline" className="h-auto justify-start gap-3 py-4" asChild>
            <Link href={href}>
              <Icon className="h-5 w-5 shrink-0 text-primary" />
              <span className="font-medium">{label}</span>
            </Link>
          </Button>
        ))}
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Latest friction summaries</CardTitle>
          <CardDescription>Generated by /api/cron/behavior-friction (24h window).</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {data.latestFriction.length === 0 ?
            <p className="text-sm text-muted-foreground">No friction reports yet. Run the cron job or wait for the next schedule.</p>
          : data.latestFriction.map((f) => (
              <div key={f.id} className="rounded-lg border p-3 text-sm space-y-1">
                <div className="flex flex-wrap items-center gap-2">
                  <Badge variant="secondary">Rage {f.rageClicks ?? 0}</Badge>
                  <Badge variant="outline">Dead {f.deadClicks ?? 0}</Badge>
                  <span className="text-xs text-muted-foreground truncate max-w-full">{f.page}</span>
                </div>
                <p className="text-muted-foreground">{f.summary}</p>
              </div>
            ))
          }
        </CardContent>
      </Card>
    </div>
  );
}
