import type { PersonaStrategyLayer } from "./offerEngineTypes";

/** Persona Strategy Layer defaults for Offer Engine locked personas (safe, non-guarantee framing). */
export const OFFER_ENGINE_PERSONA_STRATEGY_BY_ID: Partial<Record<string, PersonaStrategyLayer>> = {
  marcus: {
    businessTypeLabel: "Skilled trades owner (field service)",
    revenueRange: "$3K–$12K/month",
    mainFrustration: "Inconsistent inbound calls and a booking path that leaks after-hours demand.",
    desiredOutcome: "Steady booked jobs from search + referrals without living in the inbox.",
    commonObjections: ["We get enough referrals", "Marketing burned us before"],
    trustTriggers: ["Local proof", "Clear scope and timeline", "Trades-relevant examples"],
    buyingTriggers: ["Seasonal dip", "New competitor on the map", "Partner pushing for consistency"],
    lowBudgetConcerns: ["Paying for vanity vs booked work", "Tools that need a full-time admin"],
    diyTendencies: ["Patch the website on weekends", "Buy leads instead of fixing conversion"],
    emotionalWordingPatterns: ["no fluff", "booked jobs", "while you’re on a truck"],
    preferredCtaStyle: "Book a short call — optional audit first",
    preferredLeadMagnetTypes: ["checklist", "audit", "scorecard"],
    preferredOfferStyles: ["Done For You systems", "productized_service"],
    urgencyStyle: "Seasonal / payroll reality",
    proofSensitivity: "High — wants neighbors-like proof, not agency case studies",
    commonFears: ["Wasting money on ads", "Getting overbuilt"],
    badAlternativesTried: ["Cheap site templates", "One-off SEO retainers with no CRO"],
    timeToResultExpectations: "First wins in weeks if calls and GBP are aligned — not overnight dominance.",
  },
  kristopher: {
    businessTypeLabel: "Branding / design studio owner",
    revenueRange: "$2K–$8K/month",
    mainFrustration: "Premium positioning doesn’t match pipeline; proposals drag and scope creeps.",
    desiredOutcome: "Higher-quality clients and a repeatable discovery → offer → close funnel.",
    commonObjections: ["Portfolio should speak for itself", "Don’t want to sound salesy"],
    trustTriggers: ["Craft-respectful process", "Transparent phases", "Case framing not mockups-only"],
    buyingTriggers: ["Dry spell", "Client churn to cheaper shops", "Interest in retainers"],
    lowBudgetConcerns: ["Looking ‘corporate’", "Losing creative brand voice"],
    diyTendencies: ["Only Instagram outbound", "Endless deck polishing"],
    emotionalWordingPatterns: ["premium clients", "productized discovery", "scope that protects craft"],
    preferredCtaStyle: "Apply or short strategy session",
    preferredLeadMagnetTypes: ["mini_guide", "scorecard", "roadmap"],
    preferredOfferStyles: ["Done With You", "strategy_session", "hybrid"],
    urgencyStyle: "Cash-flow dips between launches",
    proofSensitivity: "Medium-high — peer studios and vertical relevance",
    commonFears: ["Niching feels like shrinking the business"],
    badAlternativesTried: ["Fiverr price races", "Random funnel courses"],
    timeToResultExpectations: "Pipeline signals in a few sales cycles; positioning compounds over quarters.",
  },
  tasha: {
    businessTypeLabel: "Beauty / personal care business owner",
    revenueRange: "$2K–$6K/month",
    mainFrustration: "Algorithm-dependent bookings, no-shows, weak mid-week fill.",
    desiredOutcome: "Automated booking + retention so revenue isn’t hostage to social reach.",
    commonObjections: ["Clients are only on Instagram", "No time for a site"],
    trustTriggers: ["Simple guest experience", "SMS/email cadences that feel personal"],
    buyingTriggers: ["No-show spike", "Salon suite competition", "Adding staff/chairs"],
    lowBudgetConcerns: ["Over-automation feeling cold"],
    diyTendencies: ["DM booking", "Paper lists"],
    emotionalWordingPatterns: ["booked chair time", "fill Tuesday-Thursday", "repeat visits"],
    preferredCtaStyle: "Download checklist → book consult",
    preferredLeadMagnetTypes: ["checklist", "planner", "email_course"],
    preferredOfferStyles: ["productized_service", "done_with_you"],
    urgencyStyle: "Slow season or rent pressure",
    proofSensitivity: "High for local and visual — before/after and review workflows",
    commonFears: ["Sounding spammy with reminders"],
    badAlternativesTried: ["Booking-only apps with no marketing", "Boosting random posts"],
    timeToResultExpectations: "Quick operational wins in days; marketing compounding over 4–8 weeks.",
  },
  devon: {
    businessTypeLabel: "Early SaaS founder",
    revenueRange: "$0–$3K/month",
    mainFrustration: "Broad messaging, weak landing clarity, experiments not tied to learning loops.",
    desiredOutcome: "First repeatable acquisition path: clearer ICP pages, credible story, test cadence.",
    commonObjections: ["Ship product first", "Can’t afford help yet"],
    trustTriggers: ["Honest scope for stage", "Instrumentation and hypotheses documented"],
    buyingTriggers: ["Investor conversations", "Stalled trials", "Competitor noise"],
    lowBudgetConcerns: ["Agency overhead vs runway"],
    diyTendencies: ["Copy from competitors", "Hacking analytics without events"],
    emotionalWordingPatterns: ["validation", "experiment", "next test", "readable metrics"],
    preferredCtaStyle: "Start diagnostic → strategy call",
    preferredLeadMagnetTypes: ["scorecard", "diagnostic_tool", "mini_guide"],
    preferredOfferStyles: ["strategy_session", "hybrid", "starter_offer"],
    urgencyStyle: "Runway / launch windows",
    proofSensitivity: "High on methodology; skeptical of vanity traffic",
    commonFears: ["Building the wrong funnel before PMF"],
    badAlternativesTried: ["Generic website agencies", "Unscoped ad spend"],
    timeToResultExpectations: "Learning milestones in 2–4 weeks; revenue impact depends on product pull.",
  },
  andre: {
    businessTypeLabel: "Consultant / freelancer (expert services)",
    revenueRange: "$3K–$10K/month",
    mainFrustration: "Authority doesn’t match pipeline; proposals lose to cheaper generalists.",
    desiredOutcome: "Higher conversion rates, fewer bad-fit leads, offers packaged for premium fees.",
    commonObjections: ["LinkedIn is enough", "Don’t want to niche"],
    trustTriggers: ["Thought leadership packaged as systems", "Diagnostic before deep scope"],
    buyingTriggers: ["Rate compression", "Calendar gaps", "Inbound tire-kickers"],
    lowBudgetConcerns: ["Looking like a course bro"],
    diyTendencies: ["Long bespoke proposals", "Underpricing discovery"],
    emotionalWordingPatterns: ["authority without arrogance", "diagnostic", "scope that protects your time"],
    preferredCtaStyle: "Request audit → book call",
    preferredLeadMagnetTypes: ["worksheet", "script_pack", "audit"],
    preferredOfferStyles: ["paid_audit", "strategy_session", "productized_service"],
    urgencyStyle: "Proposal season or tax/calendar year planning",
    proofSensitivity: "Very high — peer proof and methodology",
    commonFears: ["Commoditization"],
    badAlternativesTried: ["Cold templates", "Bro-marketing funnels"],
    timeToResultExpectations: "Positioning refinements show in close rates over several conversations.",
  },
};
